"""Simulation engine for SentinelFly drone surveillance frames."""

from __future__ import annotations

from datetime import date, datetime, time
from typing import Any


Frame = dict[str, Any]


_BASE_LATITUDE = 37.4219
_BASE_LONGITUDE = -122.0840


_EVENT_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "time": time(0, 5),
        "location": "Main gate",
        "object_type": "person",
        "object_color": "dark jacket",
        "object_details": "Person standing near pedestrian entrance after midnight",
        "activity": "Loitering near main gate after midnight",
        "risk_hint": "high: after-hours loitering at access point",
        "lat_offset": 0.0002,
        "lon_offset": -0.0003,
        "altitude": 118,
        "drone_speed": 12,
    },
    {
        "time": time(0, 42),
        "location": "North fence line",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Clear fence line with no visible movement",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0010,
        "lon_offset": -0.0007,
        "altitude": 124,
        "drone_speed": 16,
    },
    {
        "time": time(1, 18),
        "location": "Restricted area perimeter",
        "object_type": "vehicle",
        "object_color": "white",
        "object_details": "White van stopped near restricted area service road",
        "activity": "Stationary vehicle near restricted area",
        "risk_hint": "high: vehicle near restricted area",
        "lat_offset": -0.0008,
        "lon_offset": 0.0009,
        "altitude": 111,
        "drone_speed": 9,
    },
    {
        "time": time(2, 4),
        "location": "West loading dock",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Loading dock is quiet with no personnel present",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": -0.0004,
        "lon_offset": -0.0011,
        "altitude": 120,
        "drone_speed": 15,
    },
    {
        "time": time(2, 47),
        "location": "Main gate",
        "object_type": "vehicle",
        "object_color": "blue",
        "object_details": "Blue Ford F150 entering gate without scheduled arrival note",
        "activity": "Vehicle entering main gate",
        "risk_hint": "medium: unscheduled gate entry",
        "lat_offset": 0.0001,
        "lon_offset": -0.0004,
        "altitude": 113,
        "drone_speed": 10,
    },
    {
        "time": time(3, 33),
        "location": "South parking lot",
        "object_type": "vehicle",
        "object_color": "silver",
        "object_details": "Silver sedan parked in visitor lot",
        "activity": "Parked car observed",
        "risk_hint": "low: parked vehicle in expected area",
        "lat_offset": -0.0010,
        "lon_offset": 0.0001,
        "altitude": 122,
        "drone_speed": 14,
    },
    {
        "time": time(4, 22),
        "location": "East service road",
        "object_type": "person",
        "object_color": "gray hoodie",
        "object_details": "Person moving quickly away from service road camera line",
        "activity": "Person running",
        "risk_hint": "medium: rapid movement during low-traffic hours",
        "lat_offset": 0.0008,
        "lon_offset": 0.0012,
        "altitude": 116,
        "drone_speed": 18,
    },
    {
        "time": time(5, 10),
        "location": "North fence line",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Fence line remains clear before shift change",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0011,
        "lon_offset": -0.0009,
        "altitude": 126,
        "drone_speed": 17,
    },
    {
        "time": time(6, 2),
        "location": "Employee entrance",
        "object_type": "person",
        "object_color": "yellow vest",
        "object_details": "Maintenance worker arriving for scheduled facilities inspection",
        "activity": "Maintenance worker check-in",
        "risk_hint": "low: expected maintenance activity",
        "lat_offset": 0.0005,
        "lon_offset": -0.0002,
        "altitude": 109,
        "drone_speed": 11,
    },
    {
        "time": time(6, 49),
        "location": "Delivery gate",
        "object_type": "vehicle",
        "object_color": "brown",
        "object_details": "Delivery vehicle waiting at authorized delivery gate",
        "activity": "Delivery vehicle arrival",
        "risk_hint": "low: expected delivery window",
        "lat_offset": 0.0003,
        "lon_offset": -0.0013,
        "altitude": 108,
        "drone_speed": 8,
    },
    {
        "time": time(7, 25),
        "location": "Main gate",
        "object_type": "vehicle",
        "object_color": "blue",
        "object_details": "Blue Ford F150 seen again near main gate outbound lane",
        "activity": "Repeated suspicious vehicle appearance",
        "risk_hint": "medium: repeated unscheduled vehicle appearance",
        "lat_offset": 0.0002,
        "lon_offset": -0.0005,
        "altitude": 112,
        "drone_speed": 13,
    },
    {
        "time": time(8, 6),
        "location": "Visitor parking",
        "object_type": "vehicle",
        "object_color": "red",
        "object_details": "Red compact car parked in marked visitor space",
        "activity": "Parked car observed",
        "risk_hint": "low: normal business-hours parking",
        "lat_offset": -0.0012,
        "lon_offset": 0.0002,
        "altitude": 119,
        "drone_speed": 13,
    },
    {
        "time": time(8, 53),
        "location": "Warehouse entrance",
        "object_type": "person",
        "object_color": "orange vest",
        "object_details": "Warehouse employee moving pallets through entrance",
        "activity": "Routine warehouse movement",
        "risk_hint": "low: expected operational activity",
        "lat_offset": -0.0005,
        "lon_offset": -0.0008,
        "altitude": 115,
        "drone_speed": 12,
    },
    {
        "time": time(9, 37),
        "location": "Restricted area perimeter",
        "object_type": "vehicle",
        "object_color": "white",
        "object_details": "White van passes restricted area for second time",
        "activity": "Repeated suspicious vehicle appearance",
        "risk_hint": "high: repeat pass near restricted area",
        "lat_offset": -0.0007,
        "lon_offset": 0.0010,
        "altitude": 114,
        "drone_speed": 11,
    },
    {
        "time": time(10, 14),
        "location": "Central courtyard",
        "object_type": "none",
        "object_color": "none",
        "object_details": "No visible activity in central courtyard",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0000,
        "lon_offset": 0.0000,
        "altitude": 128,
        "drone_speed": 16,
    },
    {
        "time": time(10, 58),
        "location": "East service road",
        "object_type": "person",
        "object_color": "blue uniform",
        "object_details": "Security officer walking standard patrol route",
        "activity": "Routine security patrol",
        "risk_hint": "low: authorized patrol",
        "lat_offset": 0.0009,
        "lon_offset": 0.0010,
        "altitude": 117,
        "drone_speed": 10,
    },
    {
        "time": time(11, 42),
        "location": "Delivery gate",
        "object_type": "vehicle",
        "object_color": "white",
        "object_details": "Small delivery van checked in with loading dock appointment",
        "activity": "Delivery vehicle arrival",
        "risk_hint": "low: verified delivery activity",
        "lat_offset": 0.0004,
        "lon_offset": -0.0012,
        "altitude": 107,
        "drone_speed": 9,
    },
    {
        "time": time(12, 26),
        "location": "South parking lot",
        "object_type": "vehicle",
        "object_color": "black",
        "object_details": "Black SUV parked across two spaces near employee lot",
        "activity": "Parked car observed",
        "risk_hint": "low: parking anomaly only",
        "lat_offset": -0.0011,
        "lon_offset": 0.0000,
        "altitude": 121,
        "drone_speed": 12,
    },
    {
        "time": time(13, 8),
        "location": "Fuel storage perimeter",
        "object_type": "person",
        "object_color": "green jacket",
        "object_details": "Person paused near fuel storage perimeter fence",
        "activity": "Loitering near restricted perimeter",
        "risk_hint": "medium: loitering near sensitive area",
        "lat_offset": -0.0013,
        "lon_offset": 0.0013,
        "altitude": 116,
        "drone_speed": 10,
    },
    {
        "time": time(13, 55),
        "location": "North fence line",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Fence line clear during afternoon patrol",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0012,
        "lon_offset": -0.0008,
        "altitude": 125,
        "drone_speed": 15,
    },
    {
        "time": time(14, 31),
        "location": "Main gate",
        "object_type": "vehicle",
        "object_color": "blue",
        "object_details": "Blue Ford F150 passes main gate camera for third time",
        "activity": "Repeated suspicious vehicle appearance",
        "risk_hint": "high: recurring unscheduled vehicle pattern",
        "lat_offset": 0.0002,
        "lon_offset": -0.0004,
        "altitude": 112,
        "drone_speed": 12,
    },
    {
        "time": time(15, 16),
        "location": "Maintenance shed",
        "object_type": "person",
        "object_color": "yellow vest",
        "object_details": "Maintenance worker exiting shed with tool bag",
        "activity": "Maintenance worker activity",
        "risk_hint": "low: expected facilities work",
        "lat_offset": -0.0002,
        "lon_offset": 0.0007,
        "altitude": 110,
        "drone_speed": 11,
    },
    {
        "time": time(16, 3),
        "location": "Restricted area perimeter",
        "object_type": "vehicle",
        "object_color": "white",
        "object_details": "White van idling near restricted area access road",
        "activity": "Stationary vehicle near restricted area",
        "risk_hint": "high: repeated vehicle near restricted area",
        "lat_offset": -0.0008,
        "lon_offset": 0.0009,
        "altitude": 113,
        "drone_speed": 8,
    },
    {
        "time": time(16, 44),
        "location": "West loading dock",
        "object_type": "vehicle",
        "object_color": "gray",
        "object_details": "Freight truck leaving loading dock after pickup",
        "activity": "Delivery vehicle departure",
        "risk_hint": "low: expected logistics activity",
        "lat_offset": -0.0005,
        "lon_offset": -0.0010,
        "altitude": 109,
        "drone_speed": 10,
    },
    {
        "time": time(17, 28),
        "location": "Employee entrance",
        "object_type": "person",
        "object_color": "black backpack",
        "object_details": "Employee walking quickly toward shuttle pickup",
        "activity": "Routine employee departure",
        "risk_hint": "low: normal shift-change movement",
        "lat_offset": 0.0006,
        "lon_offset": -0.0001,
        "altitude": 113,
        "drone_speed": 12,
    },
    {
        "time": time(18, 11),
        "location": "East service road",
        "object_type": "person",
        "object_color": "dark hoodie",
        "object_details": "Person running away from east service road after patrol pass",
        "activity": "Person running",
        "risk_hint": "medium: evasive movement near service road",
        "lat_offset": 0.0008,
        "lon_offset": 0.0011,
        "altitude": 116,
        "drone_speed": 18,
    },
    {
        "time": time(18, 57),
        "location": "Visitor parking",
        "object_type": "vehicle",
        "object_color": "blue",
        "object_details": "Blue Ford F150 parked briefly in visitor parking",
        "activity": "Repeated suspicious vehicle appearance",
        "risk_hint": "high: fourth appearance of unscheduled vehicle",
        "lat_offset": -0.0012,
        "lon_offset": 0.0002,
        "altitude": 119,
        "drone_speed": 9,
    },
    {
        "time": time(19, 36),
        "location": "Central courtyard",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Courtyard clear after business hours",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0000,
        "lon_offset": 0.0000,
        "altitude": 127,
        "drone_speed": 16,
    },
    {
        "time": time(20, 19),
        "location": "Main gate",
        "object_type": "person",
        "object_color": "navy jacket",
        "object_details": "Person waiting near main gate intercom after hours",
        "activity": "Loitering near main gate",
        "risk_hint": "medium: after-hours gate presence",
        "lat_offset": 0.0002,
        "lon_offset": -0.0003,
        "altitude": 115,
        "drone_speed": 10,
    },
    {
        "time": time(21, 7),
        "location": "Restricted area perimeter",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Restricted area perimeter clear during night patrol",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": -0.0008,
        "lon_offset": 0.0010,
        "altitude": 123,
        "drone_speed": 15,
    },
    {
        "time": time(22, 2),
        "location": "South parking lot",
        "object_type": "vehicle",
        "object_color": "white",
        "object_details": "White van parked with lights off near far corner of lot",
        "activity": "Stationary vehicle after hours",
        "risk_hint": "medium: after-hours parked van",
        "lat_offset": -0.0011,
        "lon_offset": 0.0001,
        "altitude": 118,
        "drone_speed": 9,
    },
    {
        "time": time(22, 49),
        "location": "North fence line",
        "object_type": "person",
        "object_color": "dark clothing",
        "object_details": "Person walking along exterior fence line",
        "activity": "Perimeter approach",
        "risk_hint": "high: after-hours movement along fence",
        "lat_offset": 0.0012,
        "lon_offset": -0.0009,
        "altitude": 117,
        "drone_speed": 14,
    },
    {
        "time": time(23, 31),
        "location": "Main gate",
        "object_type": "none",
        "object_color": "none",
        "object_details": "Main gate clear at final patrol pass",
        "activity": "Empty patrol frame",
        "risk_hint": "low: normal patrol",
        "lat_offset": 0.0001,
        "lon_offset": -0.0004,
        "altitude": 121,
        "drone_speed": 15,
    },
]


def generate_surveillance_frames(simulation_date: date | None = None) -> list[Frame]:
    """Generate realistic drone surveillance frames across a full day."""
    active_date = simulation_date or date.today()
    frames: list[Frame] = []

    for index, event in enumerate(_EVENT_BLUEPRINTS, start=1):
        timestamp = datetime.combine(active_date, event["time"])
        frames.append(
            {
                "frame_id": f"SF-{index:04d}",
                "timestamp": timestamp.isoformat(timespec="minutes"),
                "location": event["location"],
                "object_type": event["object_type"],
                "object_color": event["object_color"],
                "object_details": event["object_details"],
                "activity": event["activity"],
                "risk_hint": event["risk_hint"],
                "telemetry": {
                    "latitude": round(_BASE_LATITUDE + event["lat_offset"], 6),
                    "longitude": round(_BASE_LONGITUDE + event["lon_offset"], 6),
                    "altitude": event["altitude"],
                    "drone_speed": event["drone_speed"],
                },
            }
        )

    return frames


def get_all_frames() -> list[Frame]:
    """Return all simulated surveillance frames."""
    return generate_surveillance_frames()


def get_suspicious_events() -> list[Frame]:
    """Return frames with medium or high risk indicators."""
    suspicious_markers = ("medium", "high", "suspicious", "restricted", "after-hours")
    return [
        frame
        for frame in get_all_frames()
        if any(marker in frame["risk_hint"].lower() for marker in suspicious_markers)
    ]


def get_events_by_object(object_type: str) -> list[Frame]:
    """Return frames matching an object type, such as vehicle, person, or none."""
    normalized_type = object_type.strip().lower()
    return [
        frame
        for frame in get_all_frames()
        if frame["object_type"].lower() == normalized_type
    ]


def start_simulation() -> list[Frame]:
    """Start the simulation and return generated surveillance frames."""
    return get_all_frames()
